main: clp.zkaleejoo.MaxClear
version: ${project.version}
name: MaxClear
author: ZkAleeJoo
api-version: 1.19

commands:
  maxclear:
    description: MaxClear main command - reload, clear, get
    aliases: [mc]

permissions:
  maxclear.admin:
    description: Administrator permissions for MaxClear
    default: op